# Set up the base box

FROM debian:stretch


ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y --no-install-recommends git wget unzip sudo pandoc openjdk-8-jdk r-base \
	bzip2 gcc g++ coreutils lsb-release curl libcurl4-openssl-dev 
